package waffle

import (
	"context"
	"io"
	"testing"
)

// reportJSX is a single-page, data-driven report — a title block, a wide
// holdings table, a two-column summary table, and a footer — rendered with the
// standard 14 fonts and no external assets. It exercises the full pipeline
// (goja/React execution → waffle-tree → stylesheet → flexbox → paint → PDF)
// without asset decoding, so it measures the engine itself.
//
// Run:
//
//	GOTOOLCHAIN=local go test -bench . -benchmem -run '^$' .
const reportJSX = `
import { Document, Page, View, Text } from '@waffle/react';

const th = { flex: 1, fontSize: 9, fontFamily: 'Helvetica-Bold', color: '#ffffff', paddingVertical: 4, paddingHorizontal: 6 };
const td = { flex: 1, fontSize: 9, paddingVertical: 3, paddingHorizontal: 6 };

function Table({ title, head, rows }) {
  return (
    <View style={{ marginBottom: 14, border: '0.75pt solid #2b3a4a' }}>
      <Text style={{ fontSize: 11, fontFamily: 'Helvetica-Bold', backgroundColor: '#eef2f6', paddingVertical: 4, paddingHorizontal: 6 }}>{title}</Text>
      <View style={{ flexDirection: 'row', backgroundColor: '#2b3a4a' }}>
        {head.map((h, i) => <Text key={i} style={{ ...th, textAlign: i === 0 ? 'left' : 'right' }}>{h}</Text>)}
      </View>
      {rows.map((r, i) => (
        <View key={i} style={{ flexDirection: 'row', backgroundColor: i % 2 ? '#f7f9fb' : '#ffffff', borderTop: '0.5pt solid #d5dbe2' }}>
          {r.map((c, j) => <Text key={j} style={{ ...td, textAlign: j === 0 ? 'left' : 'right' }}>{c}</Text>)}
        </View>
      ))}
    </View>
  );
}

export default function Report({ account, period, holdings, summary }) {
  return (
    <Document title="Financial Report">
      <Page size="A4" style={{ padding: 42, fontFamily: 'Helvetica', fontSize: 10 }}>
        <Text style={{ fontSize: 18, fontFamily: 'Helvetica-Bold', color: '#2b3a4a' }}>Financial Report</Text>
        <Text style={{ fontSize: 9, color: '#666666', marginBottom: 16 }}>Account {account} · Period {period}</Text>
        <Table title="Holdings" head={['Instrument', 'Qty', 'Avg Price', 'Value']} rows={holdings} />
        <Table title="Summary" head={['Item', 'Amount']} rows={summary} />
        <Text style={{ position: 'absolute', bottom: 24, left: 42, right: 42, fontSize: 8, color: '#999999', textAlign: 'center' }}>
          Generated by waffle · for benchmarking only
        </Text>
      </Page>
    </Document>
  );
}
`

func reportProps() map[string]any {
	holdings := make([][]string, 0, 12)
	rows := [][]string{
		{"INFY", "120", "1,432.50", "1,71,900.00"},
		{"TCS", "45", "3,890.10", "1,75,054.50"},
		{"HDFCBANK", "210", "1,644.75", "3,45,397.50"},
		{"RELIANCE", "80", "2,930.00", "2,34,400.00"},
		{"ITC", "500", "441.20", "2,20,600.00"},
		{"SBIN", "260", "812.35", "2,11,211.00"},
		{"WIPRO", "300", "489.60", "1,46,880.00"},
		{"LT", "60", "3,512.85", "2,10,771.00"},
		{"BHARTIARTL", "150", "1,205.40", "1,80,810.00"},
		{"ASIANPAINT", "70", "2,988.15", "2,09,170.50"},
		{"MARUTI", "18", "12,410.00", "2,23,380.00"},
		{"TITAN", "95", "3,301.25", "3,13,618.75"},
	}
	holdings = append(holdings, rows...)
	return map[string]any{
		"account":  "AB1234",
		"period":   "Q1 FY2026-27",
		"holdings": holdings,
		"summary": [][]string{
			{"Invested value", "24,10,033.25"},
			{"Current value", "26,43,193.25"},
			{"Unrealised P&L", "+2,33,160.00"},
			{"Realised P&L", "+58,912.40"},
			{"Dividends", "31,240.00"},
		},
	}
}

// BenchmarkLoadTemplate measures the one-time compile: esbuild transpile+bundle
// plus goja program compilation. Paid once per Template, amortized over renders.
func BenchmarkLoadTemplate(b *testing.B) {
	src := []byte(reportJSX)
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		if _, err := LoadTemplate(src, TemplateOptions{Filename: "report.jsx"}); err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkRenderReport measures one full render of the single-page report:
// React executes on a fresh goja VM, the tree is laid out, and the PDF is
// written. No external assets, standard fonts only.
func BenchmarkRenderReport(b *testing.B) {
	tmpl, err := LoadTemplate([]byte(reportJSX), TemplateOptions{Filename: "report.jsx"})
	if err != nil {
		b.Fatal(err)
	}
	props := reportProps()
	ctx := context.Background()
	if _, err := tmpl.Render(ctx, props, io.Discard); err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if _, err := tmpl.Render(ctx, props, io.Discard); err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkRenderTreeReport renders the report from its pre-serialized
// waffle-tree/v1 JSON — no React/goja execution — isolating the Go pipeline
// (contract → tree → stylesheet → flexbox → paint → PDF).
func BenchmarkRenderTreeReport(b *testing.B) {
	tmpl, err := LoadTemplate([]byte(reportJSX), TemplateOptions{Filename: "report.jsx"})
	if err != nil {
		b.Fatal(err)
	}
	treeJSON, err := tmpl.Tree(reportProps())
	if err != nil {
		b.Fatal(err)
	}
	ctx := context.Background()
	if _, err := RenderTree(ctx, treeJSON, io.Discard); err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if _, err := RenderTree(ctx, treeJSON, io.Discard); err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkRenderReportParallel renders the report concurrently across
// GOMAXPROCS goroutines from one shared Template.
func BenchmarkRenderReportParallel(b *testing.B) {
	tmpl, err := LoadTemplate([]byte(reportJSX), TemplateOptions{Filename: "report.jsx"})
	if err != nil {
		b.Fatal(err)
	}
	props := reportProps()
	ctx := context.Background()
	if _, err := tmpl.Render(ctx, props, io.Discard); err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			if _, err := tmpl.Render(ctx, props, io.Discard); err != nil {
				b.Fatal(err)
			}
		}
	})
}
