// invoice.jsx — a data-driven invoice authored in React exactly as a react-pdf
// user would write it. No React import is needed (automatic JSX runtime); props
// are supplied by the Go program in main.go and the whole thing renders on goja.
import { Document, Page, View, Text } from '@waffle/react';

const money = (n) => '$' + n.toFixed(2);

function Row({ cells, header, last }) {
  return (
    <View
      style={{
        flexDirection: 'row',
        paddingVertical: 6,
        borderBottom: last ? '' : '1pt solid #e0e0e0',
      }}
    >
      {cells.map((c, i) => (
        <Text
          key={i}
          style={{
            flex: i === 0 ? 3 : 1,
            fontSize: 10,
            fontFamily: header ? 'Helvetica-Bold' : 'Helvetica',
            color: header ? '#1d3557' : '#333',
            textAlign: i === 0 ? 'left' : 'right',
          }}
        >
          {c}
        </Text>
      ))}
    </View>
  );
}

export default function Invoice({ seller, customer, number, items }) {
  const subtotal = items.reduce((s, it) => s + it.qty * it.price, 0);
  const tax = subtotal * 0.08;
  const total = subtotal + tax;

  return (
    <Document title={`Invoice ${number}`} author={seller}>
      <Page size="A4" style={{ padding: 40, fontFamily: 'Helvetica' }}>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 }}>
          <Text style={{ fontSize: 24, fontFamily: 'Helvetica-Bold', color: '#1d3557' }}>{seller}</Text>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={{ fontSize: 16, fontFamily: 'Helvetica-Bold' }}>INVOICE</Text>
            <Text style={{ fontSize: 10, color: '#666' }}>#{number}</Text>
          </View>
        </View>

        <Text style={{ fontSize: 10, color: '#666', marginBottom: 16 }}>Billed to: {customer}</Text>

        <Row header cells={['Description', 'Qty', 'Unit', 'Amount']} />
        {items.map((it, i) => (
          <Row
            key={i}
            last={i === items.length - 1}
            cells={[it.name, String(it.qty), money(it.price), money(it.qty * it.price)]}
          />
        ))}

        <View style={{ alignItems: 'flex-end', marginTop: 16, gap: 4 }}>
          <Text style={{ fontSize: 10, color: '#666' }}>Subtotal: {money(subtotal)}</Text>
          <Text style={{ fontSize: 10, color: '#666' }}>Tax (8%): {money(tax)}</Text>
          <Text style={{ fontSize: 14, fontFamily: 'Helvetica-Bold', color: '#1d3557' }}>
            Total: {money(total)}
          </Text>
        </View>

        <Text
          fixed
          render="Invoice generated by waffle · page {pageNumber} of {totalPages}"
          style={{ position: 'absolute', bottom: 20, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#999' }}
        />
      </Page>
    </Document>
  );
}
